matrix:
 include:
  - os: linux
    dist: xenial
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
  - os: linux
    dist: xenial # or later
    language: python
    python: 3.7
  - os: linux
    dist: xenial # or later
    language: python
    python: 3.8
  - os: linux
    dist: xenial # or later
    language: python
    python: 3.9-dev
  - os: linux
    dist: xenial
    language: java
    jdk: openjdk8
  - os: linux
    language: java
    jdk: openjdk9
  - os: linux
    language: java
    jdk: openjdk10
  - os: linux
    language: java
    jdk: openjdk11
  - os: linux
    language: java
    jdk: openjdk12
  - os: linux
    language: java
    jdk: openjdk13
  - os: linux
    language: java
    jdk: openjdk14
  - os: osx
    language: generic

script: python3 ./setup.py test

